# Workflow Name
name: First Workflow
# Triggering Event ( it can by triggered by git push or manually by adding on: [push, workflow_dispatch] )
on: [push, workflow_dispatch]
jobs:
  # Job name
  first-job:
    # Environment Type
    runs-on: ubuntu-latest
    steps:
        # Step Name
      - name: First Job - Primery Greeting
        # Action to perform ( Primery Greeting )
        run: echo "Hello World!"
      - name: Multi Liner
        # Action to perform ( Multi-Liner )  
        run: |
          echo "First output........!"
          echo "Second output.......................:"
  second-job:
    # Apply sequesnce by useing needs ( needs: << name of previous job >> like ( needs: first-job ) )
    needs: first-job
    # Environment Type
    runs-on: ubuntu-latest
    steps:
        # Step Name
      - name: Print goodbye
        # Action to perform ( Goodby )
        run: echo "Done - bye!"
