# Workflow Name
name: First Workflow
# Triggering Event
on: workflow_dispatch
jobs:
  # Job name
  first-job:
    # Environment Type
    runs-on: ubuntu-latest
    steps:
        # Step Name
      - name: Print greeting
        run: echo "Hello World!"
        # Action to perform
      - name: Multi Liner  
        run: |
          echo "First output........!"
          echo "Second output.......................:"
      - name: Print goodbye
        run: echo "Done - bye!"
